apiVersion: v1
kind: Pod
metadata:
  name: mongo
spec:
  containers:
  - image: mongo
    name: mongo
    volumeMounts:
    - name: volume-data
      mountPath: /data/db
  volumes:
  - name: volume-data
    emptyDir: {}
