kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc
spec:
  containers:
  - image: mongo
    name: mongo
    volumeMounts:
    - name: volume-db
      mountPath: /data/db
  volumes:
  - name: volume-db
    persistentVolumeClaim:
      claimName: claim
