apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  replicas: 2
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: proxy
        image: nginx:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: config
          mountPath: "/etc/nginx/"
      - name: www
        image: devopstestlab/nginx-helloworld
        ports:
        - containerPort: 80
      volumes:
      - name: config
        configMap:
          name: nginx-config
