apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  replicas: 2
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: www
        image: nginx:latest
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: log_level
        - name: CACHE
          valueFrom:
            configMapKeyRef:
              name: app-config-env
              key: cache
