apiVersion: v1
kind: Pod
metadata:
  name: mylog
spec:
  containers:
  - name: mycontainer
    image: alpine
    command:
      - "sh"
      - "-c"
      - "while true; do echo $(date); sleep 1; done"
