apiVersion: v1
kind: Pod
metadata:
  name: previous-mylog
spec:
  containers:
  - name: mycontainer
    image: alpine
    command:
      - "sh"
      - "-c"
      - "echo 'previous container'"
  restartPolicy: Never
