apiVersion: v1
kind: Pod
metadata:
  name: ready-pod
spec:
  containers:
  - name: www
    image: devopstestlab/webserver-liveprobe
    ports:
    - containerPort: 5000
    readinessProbe:
      initialDelaySeconds: 10
      httpGet:
        path: /healthy
        port: 5000
