Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/trusty64"
	# Ensure that all Vagrant machines will use the same SSH key pair.
	config.ssh.insert_key = false
	config.vm.provision "ansible" do |ansible|
		ansible.verbose = "v"
		ansible.playbook = "playbook_vagrant.yml"
	end
end
