kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-dev-pods
  namespace: development
subjects:
- kind: User
  name: luc
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-pod-reader
  apiGroup: rbac.authorization.k8s.io
